package Heroes.HeroActions;

public enum DefenceTypes {
    JUMPBACK,
    JUMPLEFT,
    JUMPRIGHT,

    COUNTERHOOKPUNCH_ROUNDKICK_HOOKKICK,
    COUNTERJAB,
    COUNTERUPPERCUT,
    COUNTERSUCKERPUNCH,
    COUNTERKICK_FRONT_BACK_SIDE
}
